lib/lexer.ts
lib/parser/objects.ts
lib/parser/type-parser.ts
lib/vhdl-linter.ts
test/test_files/test_no_error/ieee2008/textio-body.vhdl

textio-body now checks correct.
Added null keyword.
Added handling of deallocate function for access type.

Fixing bugs for textio body

---

lib/parser/parser-base.ts
test/test_files/test_no_error/01/test_named_function.vhd

Named part of potential function call in assignment not interpreted as ORead but ignored.

Improved handling of function calls in extract Reads

---

test/test.ts

Currently takes 8s on my machine, so assumption was that this is fine...

Added error to test when it takes more than 10s.

---

lib/language-server.ts
lib/parser/architecture-parser.ts
lib/parser/assignment-parser.ts
lib/parser/association-list-parser.ts
lib/parser/component-parser.ts
lib/parser/concurrent-statement-parser.ts
lib/parser/context-parser.ts
lib/parser/context-reference-parser.ts
lib/parser/declarative-part-parser.ts
lib/parser/entity-parser.ts
lib/parser/instantiation-parser.ts
lib/parser/interface-list-parser.ts
lib/parser/object-declaration-parser.ts
lib/parser/objects.ts
lib/parser/package-parser.ts
lib/parser/parser-base.ts
lib/parser/parser.ts
lib/parser/process-parser.ts
lib/parser/sequential-statement-parser.ts
lib/parser/subprogram-parser.ts
lib/parser/subtype-parser.ts
lib/parser/type-parser.ts
lib/parser/use-clause-parser.ts
test/test_files/test_no_error/01/test_else_generate.vhd

Trying to phase out getNextWord in favour of getToken/consumeToken
And funky startI mathematics in favour of using the ranges of the tokens directly.
npm test felt slow though, want to find out if action runs with same speed...

Changed Object Base constructor to be based on range.

---

lib/languageFeatures/completion.ts

fixed completions of declarations from entity

---

lib/language-server.ts
lib/languageFeatures/completion.ts
lib/languageFeatures/documentHightlightHandler.ts
lib/languageFeatures/documentSymbol.ts
lib/languageFeatures/findReferencesHandler.ts
lib/languageFeatures/references.ts
lib/languageFeatures/workspaceSymbols.ts
lib/parser/architecture-parser.ts
lib/parser/component-parser.ts
lib/parser/concurrent-statement-parser.ts
lib/parser/context-parser.ts
lib/parser/declarative-part-parser.ts
lib/parser/entity-parser.ts
lib/parser/instantiation-parser.ts
lib/parser/interface-list-parser.ts
lib/parser/object-declaration-parser.ts
lib/parser/objects.ts
lib/parser/package-instantiation-parser.ts
lib/parser/package-parser.ts
lib/parser/parser-base.ts
lib/parser/sequential-statement-parser.ts
lib/parser/subprogram-parser.ts
lib/parser/subtype-parser.ts
lib/parser/type-parser.ts
lib/vhdl-entity-converter.ts
lib/vhdl-linter.ts

this allowed fixing of documentHighlightHandler

changed public text of token to a name

---

.github/workflows/todo.yml

This action checks for new TODO comments and auto creates an issue and on removal of the TODO auto closes the comment again.
Apperantly only for new comments though (works on diffs)

Add TODO action

---

test/test.ts
test/test_files/test_error_expected/01/pkg_record_child_type.vhd
test/test_files/test_error_expected/01/pkg_reference.vhd
test/test_files/test_error_expected/02_library/test_dummy.vhd
test/test_files/test_error_expected/02_library/test_library_context.vhd
test/test_files/test_error_expected/04_generic_package/generic_pkg.vhd
test/test_files/test_error_expected/04_generic_package/test_entity_generic_no_use.vhd
test/test_files/test_error_expected/04_generic_package/test_entity_generic_wrong_use.vhd

Needed to change some test cases. This can be made much better when we can selectively disable linter parts. 
But should be ok for now.
I also sneaked in much nicer printing of the error messages.

Expect exactly one error

---

lib/parser/type-parser.ts

fix ranges of record children

---

lib/language-server.ts

avoid crash with invalid additional paths

---

lib/language-server.ts
lib/languageFeatures/completion.ts
lib/project-parser.ts
lib/settings.ts
package-lock.json
package.json
test/unit_tests/completion/completion.test.ts
test/unit_tests/completion/test_completion.vhd

@g0t00 we currently have no setup for testing these ls features, correct?

added setting to complete ieee objects in lowercase

---

lib/elaborate/elaborate-global-reads.ts

removed todos

---

lib/parser/association-list-parser.ts
lib/rules/not-declared.ts
test/unit_tests/addUseStatement/__snapshots__/addUseStatement.test.ts.snap
test/unit_tests/addUseStatement/addUseStatement.test.ts
test/unit_tests/addUseStatement/generic_function_call.vhd

not declared rule not correctly recognizing port vs reference

---

.vscode/settings.json
ieee2008/standard.vhdl
lib/elaborate/elaborate-association.ts
lib/elaborate/elaborate-references.ts
lib/parser/association-list-parser.ts
lib/parser/attribute-parser.ts
lib/parser/declarative-part-parser.ts
lib/parser/expression-parser.ts
lib/parser/interfaces.ts
lib/parser/objects.ts
lib/rules/not-declared.ts
lib/vhdl-linter.ts
test/test_files/test_error_expected/12_attribute_reference/basic_test_chain.vhd
test/test_files/test_error_expected/12_attribute_reference/basic_test_chain2.vhd
test/test_files/test_error_expected/12_attribute_reference/basic_test_image.vhd
test/test_files/test_error_expected/12_attribute_reference/basic_test_length.vhd
test/test_files/test_error_expected/12_attribute_reference/basic_test_range.vhd
test/test_files/test_error_expected/12_attribute_reference/basic_test_subtype.vhd
test/test_files/test_no_error/10_expression/test_attribute_reference_chain.vhd
test/test_files/test_no_error/10_expression/test_attribute_reference_port.vhd
test/test_files/test_no_error/12_attribute_reference/basic_test.vhd
test/unit_tests/addSignal/architecture.vhd

Fixed misc bugs in write/reference handling

Added elaboration and error checking for attribute references.

---

lib/parser/file-parser.ts
test/test_files/test_no_error/01/test_library_list.vhd
test/unit_tests/libraryList/libraryList.test.ts
test/unit_tests/libraryList/test_library_list.vhd

added support for library clause with multiple libraries

---

lib/language-server.ts
lib/languageFeatures/completion.ts
lib/lexer.ts
lib/parser/assignment-parser.ts
lib/parser/parser-base.ts
lib/settings.ts
test/helper.ts
test/unit_tests/completion/completion.test.ts
test/unit_tests/completion/test_completion.vhd
test/unit_tests/completion/test_completion_record.vhd

Also try some recovering for assignment parser to get better autocomplete result.
Record elements were already suggested. But they are currently not sensitive of the already existing selected name. To do this for partial selected names is extra effort and should be separate issue/PR.

Add alias and formals to auto complete.

---

.github/workflows/release.yml

bumped release job versions

---

lib/elaborate/elaborate-selected-names.ts
lib/parser/concurrent-instantiation-parser.ts
test/unit_tests/selectedNameDefinitions/selectedName.test.ts
test/unit_tests/selectedNameDefinitions/test_protected_type.vhd

added selectedNameElaboration for protected types

---

lib/rules/empty.ts
test/test_files/test_no_error/01/configuration.vhd

fixed empty message for file with configuration

---

lib/parser/assignment-parser.ts
test/unit_tests/parser/assignment-parser.test.ts
test/unit_tests/parser/assignment-parser.vhd

Create test cases for assignment parser missing semicolon

---

lib/parser/objects.ts
lib/rules/ruleTypeResolved.ts
lib/settingsGenerated.ts
package.json
test/test_files/test_no_error/misc/test_record.vhd
test/unitTests/resolvedUnresolved/__snapshots__/resolvedUnresolved.test.ts.snap
test/unitTests/resolvedUnresolved/resolvedUnresolved.test.ts
test/unitTests/resolvedUnresolved/test_record_std_logic.vhd
test/unitTests/resolvedUnresolved/test_record_std_ulogic.vhd

add resolved/unresolved check for recordChildren

---

lib/parser/objects.ts
lib/parser/sequentialStatementParser.ts
lib/rules/ruleInstantiations.ts

rename OHasSequentialStatements to OSequenceOfStatements

---

lib/languageServer.ts
lib/rules/rulesBase.ts
lib/vhdlLinter.ts
test/unitTests/codeAction/emptyInterfaceList.test.ts
test/unitTests/namingStyle/__snapshots__/namingStyle.test.ts.snap
test/unitTests/namingStyle/generic.vhd
test/unitTests/namingStyle/namingStyle.test.ts
test/unitTests/namingStyle/unused.vhd
test/unitTests/parser/objectDeclarationParser.test.ts

do an actual renaming of the object instead of just replacing

---

lib/elaborate/elaborateInstantiations.ts
lib/elaborate/elaborateNames.ts
lib/languageFeatures/findReferencesHandler.ts
lib/parser/associationListParser.ts
lib/parser/interfacePackageParser.ts
lib/parser/interfaces.ts
lib/parser/objects.ts
lib/parser/packageInstantiationParser.ts
lib/rules/ruleInstantiations.ts
test/unitTests/rename/generic_pkg.vhd
test/unitTests/rename/rename.test.ts

Fix renaming for generic package instantiation (generic association)

---

lib/rules/ruleNotDeclared.ts

remove #176 todo

---

lib/elaborate/elaborateNames.ts

`...` rest Operator are apparently really bad for performance.
Above is before below is after (ignore the >2s boot up runs)

Some lowhanging fruits optimizing elaborateNames

---

test/vunit_compile_test_no_error.py

Re-enable OSVVM in vunit test

---

.github/workflows/vunit_compile.yml
test/docker_vunit.sh

This is what the ci runs and in my quick test it compiles our test cases in 5 instead of 15 seconds

fix vunit ci + change vunit docker to mcode

---

lib/parser/assignmentParser.ts
lib/parser/expressionParser.ts
test/test_files/test_no_error/aggregates/write_aggregate.vhd

Needed to create new PR to allow to set @Nik-Sch as reviewer

 Fix #451: assignment with aggregate write with selected name #452 

---

lib/parser/objects.ts
lib/parser/sequentialStatementParser.ts
test/test_files/test_no_error/misc/matching_case.vhd
test/unitTests/statements/case.test.ts
test/unitTests/statements/matching_case_no_end_q.vhd

Fixed handling of matching case statements

---

lib/languageFeatures/documentSymbol.ts
lib/parser/objects.ts
lib/parser/sequentialStatementParser.ts
test/test_files/test_no_error/misc/caseg_expression_braces.vhd
test/test_files/test_no_error/misc/issue476.vhd

fix documentSymbols for aggregate expressions in case statements

---

lib/languageServer.ts

Fix race-condition: closing file while parsing

---

lib/parser/fileParser.ts
lib/projectParser.ts
package.json
test/integrationTests/tortureTest/tortureTest.test.ts
test/test_files/test_error_expected/file_size/test_inst1.vhd
test/test_files/test_error_expected/file_size/test_inst2.vhd
test/test_files/test_error_expected/file_size/test_verilog.v
test/test_files/test_error_expected/file_size/test_vhdl.vhd
test/test_files/test_error_expected/file_size/vhdl-linter.yml

This is now consistently enforced in the projectParser and also in the fileParser. fixes #492

add setting for file size limit

---

lib/cli/cliUtil.ts
lib/cli/lintFolder.ts
lib/languageServer.ts
lib/linterManager.ts
lib/parser/fileParser.ts
lib/parser/objects.ts
lib/parser/parserBase.ts
lib/projectParser.ts
lib/verilogParser.ts
lib/vhdlLinter.ts
test/integrationTests/memoryLeak/randomAccess/randomAccess.test.ts
test/integrationTests/tortureTest/tortureTest.test.ts
test/test.cov.ts
test/test.ts
test/testWorker.ts
test/unitTests/documentFormatting/documentFormatting.test.ts
test/unitTests/documentSymbol/documentSymbol.test.ts
test/unitTests/lexer/lexer.test.ts
test/unitTests/parser/assignmentParser.test.ts
test/unitTests/parser/objectDeclarationParser.test.ts
test/unitTests/urlHandling/url.test.ts

I don't quite know why eslint doesn't pick up on it but my VS Code was complaining...
Do you have an idea why eslint is not complaining about the incompatible `URL` types being used?

use URL from url

---

package.json
test/integrationTests/multiRootWorkspace/code.code-workspace
test/integrationTests/multiRootWorkspace/module_a/test_entity_a.vhd
test/integrationTests/multiRootWorkspace/module_a/test_inst.vhd
test/integrationTests/multiRootWorkspace/module_b/.vscode/settings.json
test/integrationTests/multiRootWorkspace/module_b/test_entity_b.vhd
test/integrationTests/multiRootWorkspace/module_b/test_inst.vhd
test/integrationTests/multiRootWorkspace/multiRootSettings.test.ts

fix the scopes of most configuration endpoints
